import React, { useState } from 'react';
import { 
  GitPullRequest, 
  CheckCircle, 
  GitMerge, 
  User, 
  MessageSquare, 
  FileDiff, 
  CornerDownRight, 
  ShieldCheck 
} from 'lucide-react';

export default function PRWorkspace({ prData, onMergeComplete }) {
  const [prState, setPrState] = useState('open'); // 'open' | 'merged'
  const [activeSubTab, setActiveSubTab] = useState('conversation');

  if (!prData) {
    return (
      <div className="flex flex-col items-center justify-center h-[320px] rounded-xl border border-dashed border-slate-800 bg-slate-900/10 text-slate-500">
        <GitPullRequest className="w-10 h-10 mb-2 stroke-1" />
        <p className="text-sm font-mono">No Pull Request created yet.</p>
        <p className="text-xs text-slate-600 mt-1">PR will be generated by the PR Creator Agent once verification tests pass.</p>
      </div>
    );
  }

  const handleMerge = () => {
    setPrState('merged');
    if (onMergeComplete) {
      onMergeComplete();
    }
  };

  return (
    <div className="flex flex-col rounded-xl border border-slate-800 bg-slate-900/40 overflow-hidden shadow-2xl text-left">
      {/* GitHub PR Title Block */}
      <div className="p-6 bg-slate-950/80 border-b border-slate-800">
        <h1 className="text-slate-100 text-lg md:text-xl font-semibold flex flex-wrap items-center gap-2">
          <span>{prData.title}</span>
          <span className="text-slate-500 font-mono text-sm">#42</span>
        </h1>

        <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-slate-400">
          {prState === 'open' ? (
            <span className="inline-flex items-center gap-1.5 px-3 py-1 font-semibold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full">
              <GitPullRequest className="w-3.5 h-3.5" />
              Open
            </span>
          ) : (
            <span className="inline-flex items-center gap-1.5 px-3 py-1 font-semibold bg-purple-500/20 text-purple-400 border border-purple-500/30 rounded-full animate-bounce">
              <GitMerge className="w-3.5 h-3.5" />
              Merged
            </span>
          )}

          <span className="flex items-center gap-1">
            <User className="w-3.5 h-3.5 text-slate-500" />
            <strong className="text-slate-300">self-healing-agent-bot</strong> wants to merge commits
          </span>

          <div className="flex items-center gap-1.5 font-mono text-[11px] bg-slate-800 px-2 py-0.5 rounded border border-slate-700">
            <span className="text-slate-400">main</span>
            <CornerDownRight className="w-3 h-3 text-slate-500" />
            <span className="text-blue-400">{prData.branch}</span>
          </div>
        </div>
      </div>

      {/* GitHub Tabs */}
      <div className="flex border-b border-slate-800 bg-slate-950/40">
        <button
          onClick={() => setActiveSubTab('conversation')}
          className={`flex items-center gap-1.5 px-4 py-3 text-xs font-semibold border-b-2 cursor-pointer transition-all ${
            activeSubTab === 'conversation' 
              ? 'border-blue-500 text-blue-400 bg-slate-900/30' 
              : 'border-transparent text-slate-400 hover:text-slate-200'
          }`}
        >
          <MessageSquare className="w-3.5 h-3.5" />
          Conversation
        </button>
        <button
          onClick={() => setActiveSubTab('files')}
          className={`flex items-center gap-1.5 px-4 py-3 text-xs font-semibold border-b-2 cursor-pointer transition-all ${
            activeSubTab === 'files' 
              ? 'border-blue-500 text-blue-400 bg-slate-900/30' 
              : 'border-transparent text-slate-400 hover:text-slate-200'
          }`}
        >
          <FileDiff className="w-3.5 h-3.5" />
          Files changed
          <span className="bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-1.5 py-0.2 rounded-full text-[10px]">
            +1 -1
          </span>
        </button>
      </div>

      {/* PR Workspace Body */}
      <div className="p-6 bg-slate-950/20 flex-1">
        {activeSubTab === 'conversation' ? (
          <div className="space-y-6">
            {/* Bot PR Description Comment */}
            <div className="rounded-lg border border-slate-800 bg-slate-950/60 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2.5 bg-slate-900/80 border-b border-slate-800">
                <span className="text-slate-300 font-semibold text-xs flex items-center gap-1.5">
                  <span className="w-4 h-4 rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30 flex items-center justify-center text-[10px]">A</span>
                  self-healing-agent-bot
                </span>
                <span className="text-[10px] text-slate-500 font-mono">collaborator</span>
              </div>
              <div className="p-4 text-xs leading-6 text-slate-300 space-y-4 font-sans max-h-[250px] overflow-y-auto custom-scrollbar">
                {/* Format basic markdown description lines */}
                {prData.description.split('\n').map((line, idx) => {
                  if (line.startsWith('### ')) {
                    return <h3 key={idx} className="text-slate-100 font-bold text-sm mt-4 mb-2">{line.replace('### ', '')}</h3>;
                  }
                  if (line.startsWith('* ')) {
                    return <li key={idx} className="ml-4 list-disc text-slate-300">{line.replace('* ', '')}</li>;
                  }
                  if (line.startsWith('**') && line.endsWith('**')) {
                    return <p key={idx} className="font-semibold text-slate-200">{line.replace(/\*\*/g, '')}</p>;
                  }
                  return <p key={idx} className="text-slate-300">{line}</p>;
                })}
              </div>
            </div>

            {/* Checks Status Box */}
            <div className="p-4 rounded-lg border border-slate-800 bg-slate-900/60 flex items-start gap-4">
              <div className="p-1.5 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full mt-0.5">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <div className="flex-1">
                <h4 className="text-slate-200 text-xs font-semibold">All checks have passed</h4>
                <p className="text-[11px] text-slate-500 mt-1">1 successful check has been verified by the Test Agent.</p>
                <div className="mt-2.5 border-t border-slate-800 pt-2 flex items-center justify-between">
                  <span className="text-[10px] text-slate-400 font-mono flex items-center gap-1.5">
                    <CheckCircle className="w-3.5 h-3.5 text-emerald-400" />
                    verify-tests / test-suite (push) — Test case passed
                  </span>
                  <span className="text-[10px] text-slate-500 font-mono">Details</span>
                </div>
              </div>
            </div>

            {/* Merge Actions Box */}
            <div className="p-4 rounded-lg border border-slate-800 bg-slate-900/60">
              {prState === 'open' ? (
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <div>
                    <h4 className="text-slate-200 text-xs font-semibold flex items-center gap-1.5">
                      <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                      Merge is blocked by review (Simulator Mode)
                    </h4>
                    <p className="text-[11px] text-slate-500 mt-1">This branch has no conflicts with the base branch. Click "Approve & Merge" to complete the self-healing loop.</p>
                  </div>
                  <button
                    onClick={handleMerge}
                    className="flex items-center justify-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 text-slate-100 text-xs font-semibold rounded border border-emerald-500 hover:border-emerald-400 transition-all cursor-pointer shadow-lg shadow-emerald-900/20"
                  >
                    <GitMerge className="w-3.5 h-3.5" />
                    Approve & Merge PR
                  </button>
                </div>
              ) : (
                <div className="flex items-center gap-3">
                  <div className="p-1.5 bg-purple-500/20 text-purple-400 border border-purple-500/30 rounded-full">
                    <GitMerge className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-slate-200 text-xs font-semibold">Pull Request merged and closed!</h4>
                    <p className="text-[11px] text-slate-500 mt-1">
                      Automated code fixes deployed to <span className="font-mono text-slate-400">main</span> branch. The self-healing loop is closed.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        ) : (
          /* Files Changed Tab */
          <div className="rounded-lg border border-slate-800 bg-slate-950/80 p-4 font-mono text-xs overflow-x-auto custom-scrollbar text-left max-h-[350px]">
            <p className="text-slate-500 mb-2">Showing 1 changed file with 1 addition and 1 deletion:</p>
            <div className="text-slate-300 leading-5 whitespace-pre">
              {prData.diff}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
